apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manycat

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - app-deployment.yaml
  - agent-deployment.yaml
  - orchestrator-deployment.yaml
  - rbac-orchestrator.yaml
  - sandbox-job-template.yaml
  - ingress.yaml
